# Generated by Django 5.1 on 2024-08-17 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autuser', '0007_rename_username_user_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
