# Generated by Django 5.1 on 2024-08-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
