# Generated by Django 5.1 on 2024-08-17 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0006_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_name',
        ),
    ]
