# Generated by Django 5.1 on 2024-08-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0010_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background_picture',
            field=models.ImageField(blank=True, default='../static/icons/default_background.jpeg', null=True, upload_to='background_pictures/'),
        ),
    ]
